name: CI Testing PR Commit Message Listing
on: [workflow_dispatch]

jobs:
  read_type:
    runs-on: ubuntu-latest
    name: A CI job to list the Commit Messages on a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repo-token: ${{ secrets.GH_REPO_CONFIG}}
      - name: List commit messages
        id: list
        uses: ./ 
        with:
          pr-number: 1
          repo-token: ${{ secrets.GH_REPO_CONFIG}}
      - name: Display type
        id: display
        run: |
          echo ${{ steps.list.output.changelog-text}}


